name = "escolha-certa-landing-page"
compatibility_date = "2024-01-01"

[env.production]
routes = [
  { pattern = "www.escolhacertacontabil.com.br/*", zone_name = "escolhacertacontabil.com.br" }
]

# Configuração para site estático
[site]
bucket = "./dist"

# Build configuration
[build]
command = "echo 'Static site - no build required'"
cwd = "."
watch_dir = "."

# Assets configuration
[[assets]]
bucket = "."
include = ["**/*"]
exclude = [".git/**", "node_modules/**", ".gitignore", "wrangler.toml", "package-lock.json"]