name = "escolha-certa-landing-page"
compatibility_date = "2024-01-01"

# Configuração para Cloudflare Pages
pages_build_output_dir = "dist"

# Build configuration
[build]
command = "npm run build"
cwd = "."
watch_dir = "."